final_transcript = [
    {
        "text": "And I sat there listening to this, almost as in disbelief. It's like someone who's obviously privileged, but contemptuous enough to not even realize that he's been given a gift. So the first ten or twelve years of my chess career, computers were not in the picture at all. Essentially, what we knew was what humans had thought about again and what you had managed to understand out of it. In chess, everything is about space, time. That is how quickly my pieces can get somewhere. The relative value of the pieces and the positioning of the pieces.",
        "speaker": "Viswanathan Anand",
        "start": 160,
        "end": 30558,
    },
    {
        "text": "There is also a renewed interest, interest in chess, you know, that has become, I think, quite popular compared to where it was ten years ago. India has started doing so well, directly contribute to the emergence of that. He told me something I was not familiar with, this thing called Zook Zwang.",
        "speaker": "Mukesh Bansal",
        "start": 30646,
        "end": 44068,
    },
    {
        "text": "So Zhuk Zwang is the most tragic situation. So Zook is a move, and Zwang is essentially being in a situation where you're forced to do something.",
        "speaker": "Viswanathan Anand",
        "start": 44156,
        "end": 52744,
    },
    {
        "text": "Arant, welcome to Sparks. Really looking forward to this conversation.",
        "speaker": "Mukesh Bansal",
        "start": 63954,
        "end": 67934,
    },
    {
        "text": "Pleasure to join you. Mukesh.",
        "speaker": "Viswanathan Anand",
        "start": 68394,
        "end": 69706,
    },
    {
        "text": "There is also a renewed interest in chess. You know, this has become, I think, you know, quite popular compared to where it was ten years ago. There was, you know, people follow chess tournaments on the Internet. Lot of amateur players are coming in. Professional circuit, I think is also doing well. India has started doing so well. I mean, a lot of, you know, directly contribute to emergence of that. So in some ways, we were entering a pretty good, despite knowing that computers are so good, in some ways, help playing the enabling role in making the game in some ways more relevant than ever before.",
        "speaker": "Mukesh Bansal",
        "start": 69770,
        "end": 102904,
    },
    {
        "text": "Definitely, if we look at the average fan, the casual fan, and the person who just comes to the game casually, very quickly, they're able to find out what's going on at the level of the sport. Whereas 30 years ago, a decent club player, a hobby player, would be of the level to understand and enjoy the sport in its full. Now we are able to, a much broader audience is able to relate to us, and that has spawned a lot of very positive things. But the thing is, I'm probably a better player now than I was 30 years ago. But 30 years ago, I had much more self confidence in my moves. And there's good and bad. I'm now open to all sorts of concepts. I don't start with my opinion of what's good and bad. My first reaction was, let me see how I could be wrong. Maybe there's certain amount of humility baked in, and the modern generation didn't even go through that transition process. So for them, it's even more self evident. But for the sport, it's been good because even more than computers per se, the communications revolution, bandwidth, video commentary, all that has made the game more accessible. And the fact that you once had to find another chess player, you had to meet them at a club and play a game. The fact that playing has become just so frictionless. You just pull up your phone, start a game, you can stop it. Two minutes later, that level of thing has made the game boom. It's done it for India because India seems to be entering this. We are playing catch up, right? We're skipping I don't know how many industrial revolutions and we're jumping into this it revolution and somehow we are right there when mobiles are happening and just is benefiting from that as well. And that's playing a big part for India.",
        "speaker": "Viswanathan Anand",
        "start": 103284,
        "end": 223980,
    },
    {
        "text": "That's great to see. I think in India for the last 30 years, chess was synonymous with the Anand thing. That's where chess was mentioned. It was your name. But last few years, there's so many younger players also coming up. Some you very closely work with, I think five players in top 20 in the world now, which has probably never happened before. I watching one of your interviews where you basically, I think you use the phrase, this is a golden generation, something like that, which is, I think Gokesh is going to take on the world championship, correct? I think, five, six months from now. So that's, I mean, that's a testimony to, I think, both the talent in the country, but also, I guess, you know, people also need inspiration. You know, it's like I may have talent, but if I'm not inspired, I'm not going to put in the effort. So in some ways, you know, in some, I mean, you have inspired, I think, you know, millions of people and now technology and access and so on, hopefully in a little easier to make a career also out of, you know, playing chess. And it's all collision to, you know, create this phenomenal. And now it looks like it's probably going to be unstoppable. You know, there's these five guys that are probably a lot more in the pipeline. They show up in next five years down the line. So, looks like pretty interesting time for chess in the country.",
        "speaker": "Mukesh Bansal",
        "start": 224052,
        "end": 294604,
    },
    {
        "text": "Definitely. Essentially my role was maybe to start the thing. I was a reason for many Indians to maybe open the newspaper and even look, you know, what's happening in chess. And then this multiplier effect. Each one of them maybe taught it to some of their children or nephews. That generation went on to become grandmasters, international masters. Then they started to teach the subsequent generation and slowly the ripple, you know, the way rippled out. But now we have this nice coincidence that four of the best juniors, I'm talking four, five years ago, happened to all be indian and rivals of each other. And now all of them have moved into the top 20 in the world and they move in and out of the top ten. So what does. But can you imagine for them, they are the best players in the world, but they're not even sure of making the national team. And so that that keeps them on their toes. And I think it's a very big force in how competitive they are because very similar to how it once used to be in the Soviet Union. You could be one of the best players in the world and not make your national team. I think we are hitting that thing now. So, yeah, it is a golden era for chess.",
        "speaker": "Viswanathan Anand",
        "start": 294764,
        "end": 382150,
    },
    {
        "text": "Environment around you plays a big role because now you are, instead of waiting for the international tournament, you are competing with world class player basically day in, day out. I think you also mentioned somewhere else that sometimes you are not even the best player in your city, even though you are top 20 in the world, which means the role of environment around you to really pushing you is completely on top of your mind. You are figuring out a way to outsmart the person that you are going to see again tomorrow. Is creating invisible force to propel these kids to really be as good as they possibly can, I think.",
        "speaker": "Mukesh Bansal",
        "start": 382222,
        "end": 417738,
    },
    {
        "text": "Yeah, you hit the nail there. It's an invisible force. They're all thinking of the game. They're all looking at each other thinking of the game. And at some level the discussion gets more and more sophisticated and stronger. It's hard to see all, everything that's happening, but you see the end result and it is fantastic. So it is a period, I think, where India will make a stamp world of chess.",
        "speaker": "Viswanathan Anand",
        "start": 417786,
        "end": 442094,
    },
    {
        "text": "We were just talking before, we're starting out that you're basically been playing chess for almost 48 years, so going to complete half a century. And that's so fascinating to me. I tried to study about mastery, what it takes to truly understand subject and that in this case, an example of studying, practicing, learning about chess and competing at the highest level, you are still among the top 1012 players in the world. How does this whole, your understanding of game has evolved over the years? Being a student and how have you found the interest in the game again and again, instead of getting bored? I think, okay, I know everything that there is to know about this I.",
        "speaker": "Mukesh Bansal",
        "start": 442214,
        "end": 484172,
    },
    {
        "text": "Grew up in the precomputer era. Well, in the precomputer era. So the first ten or twelve years of my chess career, computers were not in the picture at all then. Essentially what we knew was what humans had thought about again and what you had managed to understand out of it. And there was a lot of difference from player to player. One player would strongly believe that one move was good in a position and another would strongly disagree. And there was scope for this kind of disagreement because it could only be settled in a game. And I would say, looking back from where we are now, there was a lot we didn't know, but we had the confidence, we were very good. And then what happened? Computers came along. Initially it was databases, so that didn't change the understanding of the game as such. But eventually chess playing programs entered the picture unbelievably weak. So they were like basic calculators at that point, but slowly. So we would do the complex work and then just do a cleaning round with the engine just to make sure we had not made some basic errors, you know, just acts of moves and negligence. But with each generation, they got better and better, and then we could hand over more and more work to them, do a thing. But still the dominant thing was I had to formulate a good plan and then try to see if it held together.",
        "speaker": "Viswanathan Anand",
        "start": 484228,
        "end": 588876,
    },
    {
        "text": "This was in nineties.",
        "speaker": "Mukesh Bansal",
        "start": 588980,
        "end": 590116,
    },
    {
        "text": "In the nineties. I'm talking 1990 till about 97. 2000 even. Even though Kasparov lost to deep blue in 97, that was still isolated from the chess world, because that's a supercomputer, and it's not like we had access to everything that it was playing, and it might not even have been that good in the first place. So the irony is the computer, which went down in history as the first to perform the task, humans could probably still have beaten it.",
        "speaker": "Viswanathan Anand",
        "start": 590260,
        "end": 621764,
    },
    {
        "text": "People are just pure brute force, just computing.",
        "speaker": "Mukesh Bansal",
        "start": 622504,
        "end": 624968,
    },
    {
        "text": "Exactly. So there was no way to say that it was, that it would always win. The trend of humans handing over work to the computer and trying to. So the nature of work started to change. I would initially hand over the basic calculation, then a lot of it, and then this allowed me the possibility to ask also interesting questions. I don't know, let's just try this path. Go down that. So you simulate things that before taking a lot of time to. You would have to find a sparring partner. They would have to understand what you're talking about, and they would. Then you would have to play a lot of games, record these games, analyze them slowly. Now you're able to do all that much faster and use it to. And around about 2006, they started trying very interesting stuff with the software so far. And what they did was at a very early stage, the computer would prune its search tree very, very fast. And this meant that it seemed human like briefly. I mean, this was a phrase which will come up often. It seemed human like briefly, in the sense that it would have these. It would trade complex concepts. So in chess, everything is about the space time. That is how quickly my pieces can get somewhere, the relative value of the pieces and the positioning of the pieces. So if my piece, I have fewer pieces, but they are all in one sector of the board, that sort of thing. And you are just trading these concepts all the time. This generation of machines with very, very interesting ways of using that brute force that they had seemed human like in the way they would seem to go off, almost. The move seemed intuitive to us. Then, once again, a period of consolidation where just very, very good engines come include some of these techniques and they're very strong. Then the first neural, so famously Alphazero. And that was a big leap because there were a couple of. A couple of foundational rules which were rewritten at this point, all the chess playing programs for the first 50 or 60 years of this attempt. So from the university days until the period I'm talking about, which lasted for about 25 years, where programmers writing programs, putting in rules, but based on human games and trying to transfer human understanding as a form of a few basic rules to the computer, Alphazero treaded a new path, which is they programmed the rules of the game, nothing more. They didn't try to explain to it what is the value of a queen or what is the value of a rook. They just gave it the rules. And then I think the stencil chips just played, machines just played 44. The number that's bandied route is 44 million games with itself. And over these 44 million games, it figured out certain rules. It understood very quickly and understood if the queen can do this and it can do this, of course, it's more valuable than the rook, it's more valuable than the knight and the pawn, of course. And very quickly it sorted out the relative values. But then it started to sort out, look, every time the queen's in a dominant position, this happens, or the knight is in this place, this happens. And when the knight is here, when the pawn is here, all these relationships started to build and it then beat the strongest old style chess engine 100 to zero. And that was very big deal. And so subsequently a lot of the best chess playing programs happen on GPU's, so very similar to what's happening in AI. And. Okay, so now to get back to the human side of the story. By this time, the computer that it beat 1000 was beating us 1000. So the gap was getting huge. And it no longer makes sense to compare because when you, when I play one generation of a computer, and I mean a program and another generation, I'm going to lose to both of them. But I have no relative sense of whether I'm doing better or worse than the previous time because you're losing by such a wide margin. It's very hard to understand that, you know, I actually played better this time, but I still lost because the gulf is too big. What we start to do now is to use the computer merely as a training tool. But anyway, to get back to the first part of the human story, now we had a much more realistic sense of where we stood in chess understanding. We understood that we're pretty good. In fact, Alphazero confirmed that the human way of playing chess was pretty good. We didn't have the tactical strength, the calculating ability to justify it to a computer, but it was not wrong. And so, you know, if that's a pat on the back for us, it's nice. But the Alvazero's conceptualization of, you know, lots of difficult concepts, chess is quite similar to how we figured it out. But by now, philosophically, no chess player even tries to contradict the computer. And you, you just assume that you don't know the answer. In fact, there are a few significant changes here. Once upon a time, it was thought that the two players who played the game were the best informed about what happened in that game and that all the spectators were merely trying to follow them in their way. By now, it's more or less just an accepted fact, a very basic accepted factor, that the two players who played the game are the least well informed about what happened. But there is one asymmetry. They are the only ones who know what transpired in the game because they are the only ones who felt lack of information. They are calculating the same moves that the spectators are calculating, seeing presented, but they don't know if they're right or wrong. So they're grappling with all that uncertainty. So the players are the only ones who know what transpired under that fog, the fog of war, the uncertainty. But everyone else has a better idea what actually was the correct move. And so once upon a time, people waited for the players to finish, to find out what happened in the game and the player would give them the information. This movie you thought was good. Now the players come to the press conference and say, by the way, what did it say? Did I miss something? And the information goes the other way. It's still. And now the people watch the press conference to find out what they didn't know. But most significantly, we have lost this confidence that our intuition is somehow amazing or refined because, you know, it's clear there are ways of very superior.",
        "speaker": "Viswanathan Anand",
        "start": 625136,
        "end": 1099446,
    },
    {
        "text": "So we understand there's a lot more in some ways, because if these programs, the traditional progress, are already beating human players and then AI is beating those 1000, which means in some way the game has huge scope to evolve. It's not that we know everything there is to know and maybe that's. And despite all these youngsters coming, which is obviously very welcome, you continue to be among the top few players in the world for consistently over, I don't know, maybe 35 years or so. I mean, that's unheard of longevity in chess. Maybe earlier era, but no longer. What is your approach to game? What do you attribute to that? Being able to stay relevant and compete at the highest level. I know you do less number of tournaments now, but still very competitive. Otherwise you would not have the rank that you have. So especially in the last decade, I think at some point maybe I should mention that four of your world championship happened, I think between 2007 and 13. And that's the highest possible level you can ever achieve. But you stayed motivated for the game. Last 1011 years, continued to compete. How is that the latter part of your career panned out.",
        "speaker": "Mukesh Bansal",
        "start": 1099510,
        "end": 1171564,
    },
    {
        "text": "So when I became world champion, it was really the culmination of a dream. I started to play in the world championship cycle in the year 1990. I became world champion for the first time in 2000. But then the chess world was divided. There were two titles, a lot of chaos. I got a chance to win the unified title in 2007 and then I had a six year reign till 2013. You know, for me, clearly that was the most important thing. You know, when the career defining goals, career defining dreams, let's say all you get, you take off one by one and it felt great. Then I got to the stage where post world championship, what should I do? The obvious thing is I should continue to compete at the top, play the best tournaments and more of a self challenge. Not because there was something left accomplished. It felt very much like some overtime. But at the same time, I still like the game. And you can't half do a sport, you either all in or you're not. So it was a learning process. I had to find a way to learn new things, suppress my ego, my understanding, and say, if young people are trying these things, well, maybe there's something I don't understand. Let me figure it out. You know, evolve with this very, very fast changing world of chess. And the next few years, I tried to do that. And then a couple of years ago in 2019, I met Sadiq Singhal in Westbridge and we got this idea. I mean, he suggested that we work together. I came up with the idea of an academy, and the first year I selected these four youngsters. Then we added one more, a fifth one, and there was the best girl. We started to have what I thought would be good habits, regular classes, some ideas, how to work. But more and more, me sharing my personal experience, see, the best variations will keep changing all the time now because a new computer will immediately uncover some new stuff. Just knowledge as such is going to keep changing all the time, but just experience more. My experiences from 30 years ago are still relevant when I talk about sitting at the board and facing an opponent and what I go through and things that's going to be relevant 50 years into the future as well. Because with all the training methods, the playing experience hasn't changed significantly. It continues to be so. The idea was for me to work with this thing, and we thought it would be nice, as I transition out of chess, for India to continue to be represented at the top. And of course, we. I mean, certainly not the only reason for these kids to do well. They are wonderful parents, setups, all that. But it feels almost like it's been too successful. And we gotten there very early, because now, after 30 years of undisputed number one, and it's hard to exaggerate just how inconceivable it seemed because there was a hundred point gap sometimes between me and the next. Yeah, recently, Hari came within sniffing distance with it, started to come within, but it just seemed axiomatic that I would be India number one. And suddenly there are four people, all of whom have overtaken me at least once. And, you know, so that's a funny place to be. But anyway, the answer to your question is, I try to keep abreast with developments impossible to be without in such a fast changing era. And I think very similar to what people in all walks of life feel that you can't say, well, this is how we used to do things. You have to keep moving yourself along and prepare yourself for the idea that not only might you be wrong, but even what you thought might have been wrong or might have been incomplete maybe is the better way of putting it.",
        "speaker": "Viswanathan Anand",
        "start": 1172824,
        "end": 1434554,
    },
    {
        "text": "I think alluded to a couple of, I think, really important lessons somewhere. I think we've talked in this podcast a few times. One is idea of this long term and compounding. It says when you do something over 45, 50 years, the kind of patterns you can see, something you did 30 years ago is also relevant, but you also seen what has evolved in last ten years. So that versus doing something for, you know, today we live in a very fast paced world. You know, people want results quickly and we want to, you know, judge ourselves after two year or five year period. But doing something, what you've done is truly, you know, matters at a world level to aspire to that. I think having that long term orientation. And second thing also, you know, learning unlearning, learning unlearning and being able to let go of, you know, probably a very concept that might have been dear to in the past. Both are probably key ingredients to why you have continued to be relevant and you found a really good sweet spot now where yourself playing and competing. So I mean, I'm sure that gives a thrill of its own, but yet you're also simultaneously teaching the next generation and helping them also kind of share the global stage with you. So that's, I think, the best of both worlds.",
        "speaker": "Mukesh Bansal",
        "start": 1434594,
        "end": 1501816,
    },
    {
        "text": "Yes, to some degree. And I think I like the way you put it that I once read about countries and somebody said all centuries coexist in many countries. You'll find in India you'll find the most modern stuff, but you'll also see some world which is not fundamentally changed from 800 years ago. And it feels like that in the brain as well. Some of my moves feel like a 1970s intuition, some feel from another decade and some feel very modern. And so there is this traffic jam in your head. But that's the thing about evolving. You're evolving, but not 100%. And parts of you continue to think in old ways. That's the advantage youngsters have. But of course eventually they'll face the same issue. But it makes the chess very interesting to follow, that's for sure.",
        "speaker": "Viswanathan Anand",
        "start": 1501960,
        "end": 1555744,
    },
    {
        "text": "There's no question about it. Let's just go back earlier part of your career. I think first time you were on the like, really on a large global stage while you started competing for the world championship, nineties onwards, 95, you set up this match with Kasper. And I think there was a last minute change in location as well. I think maybe not last minute, but supposed to be in Europe, I think I moved to New York in this cage kind of setup. And Kasparov was, he was always, I think, especially in heydays, quite a dramatic character, and even more so in this tournament with you. How was, you know, just speaking the mental side of things. How was your preparation going into it and how did that experience, you know, change you that time? I think you're probably caliber wise, you were there, you could have won that also. I think you were doing well at some point in that, you know, but in the end, you didn't. But this whole, you know, did his antiques affect you? Did you have some kind of counter measures to be able to handle it? Or later you develop so that these things stop not disturbing you to give.",
        "speaker": "Mukesh Bansal",
        "start": 1555864,
        "end": 1618846,
    },
    {
        "text": "The answer before the explanation. I would say I went into the match pretty naive, in a sense. It's impossible to prepare something that you don't have to anticipate, and it's hard to anticipate something that you can't imagine, you can't visualize. And so experience has to teach you that. Kasparov had already played five matches with Karpov alone, who tried every trick in the book against him. So Caspar had that strengthening. What he also had was growing up with Patvinek and others, interacting with them, and over time, Petroshen, all these people sharing stories of their matches and so on. So he, in that sense, he. Even in his first match, I don't think he was as innocent as I was in my first. It was supposed to be held in Cologne in Germany. Then at some point in June, suddenly they switched to New York and we were going to play in the 107th floor of the World Trade center, obviously a very prestigious venue. But I was informed. I was not consulted. And these sort of things, I didn't think. I didn't see why they needed to consult me. I didn't bother. But these things are important because they provide the stage for where everything is going to happen to you. And if so, if you're not in a role where they've. They're scared or they are worried and they feel that they have to check with you before making any changes, then continuously, people will poke around and. And it affects you eventually. In chess, someone once said that giving up the psychological space is a mistake, because then you're being pushed inward till you only have the chessboard. Whereas if you stand up for everything, again, the question is how much you should stand up and all there is scope for that. But the first match, I was very naive. People had started to tell me, but it's simply a failure of imagination. I couldn't understand why it would play a role. I think you have to feel it. Once Kasparov understood that if you slam the door, you make provocative statements at the press conference while I'm sitting there. You mock a good move while I'm sitting there, that these things sit inside your head and they irritate you and they can affect your play. He understood these little details.",
        "speaker": "Viswanathan Anand",
        "start": 1618870,
        "end": 1764320,
    },
    {
        "text": "You imagine these things in boxing matches, put in chess. These tactics are surprisingly, they work in.",
        "speaker": "Mukesh Bansal",
        "start": 1764352,
        "end": 1769096,
    },
    {
        "text": "Chess because, you know, if someone says a couple of times he played just a bad game, and I thought, well, I outplayed you. And then he would say, he made it seem as if he had taken a risk for the audience and things like that. And slowly later on, I realized you cannot draw a line from that to I played badly. But over time, I learned that you cannot dismiss it either. And there is nothing which says that if I don't reply more strongly in the press conference that I will play badly. In fact, quite the opposite. You're showing confidence, you're showing that you're in the roman song. So a lot of the psychology state of mind I paid much more attention to in subsequent matches because, you know, I'd been through the fire once.",
        "speaker": "Viswanathan Anand",
        "start": 1769120,
        "end": 1814744,
    },
    {
        "text": "And did you have to develop some kind of inner routine to be able to protect yourself and figure out how much you want it to, you know, affect you? Because maybe you want to also use as a fuel but also not too much because sometimes, you know, it can create, you know, self doubt or, you know, take you in a direction where, you know, unnecessary waste of time.",
        "speaker": "Mukesh Bansal",
        "start": 1814824,
        "end": 1833556,
    },
    {
        "text": "A couple of examples. In the first match, I used to read chess magazines just to see what was going on. And I picked up one magazine and they had interviewed seven, eight, the best players and said, what are your predictions for the Anand Kasparov match? And this would have been a good moment to flip the page. But I read it anyway, and many of them said things. Some of them were straightforward facts. I mean, Kasparo is more experienced, that's clear. And they valued that highly. And they said, well, I think Kasparov will win, but if you read nine predictions that you're most likely going to lose and then you tell yourself, okay, I don't care. But that's not the same thing as not caring. That's telling yourself. And it's a different act and you have to understand the difference. I think it could have bugged me and it could have influenced me because I was more timid in the approach in the match. And in fact, initially in the match, I'd focused on avoiding failure in the first stretch because I thought if it starts early and I don't feel comfortable yet, and the match starts to go badly, there's no time to recover, which is not a bad strategy. But the way I implemented it was kind of, and it's possible that reading all these things influenced me. So by the same, I played my second match, it was more or less obvious to me that in fact, before the training started, I told my seconds, you read the magazines, you read what's out there. I'm not going to go to any chess website. From now on. You're going to send it the chess material stripped of all the other stuff and you keep it in mind, but don't tell me. And it's your job to, you decide what's relevant and what's not and give it to me in a neutral way so that emotionally. So that was one lesson I took out, but there were many like this, and it's little details. It's realizing that you're very tense right before the game is about to start. And if your car is late, you can't get irritated because then it clouds your judgment. Once the game starts and you go to the board in a slightly irritated thing, you have to tell yourself, these things happen. I mean, there is no global conspiracy to do anything. To me, it's just the car. Another car stood in its way and it's late. You take a deep breath, you try to let go of what you can't control. I mean, positioned under that heading, it looks easy, but it breaks up a lot of little learnings. And so in each match I was able to implement these things better and hopefully I'll be able to convey it to someone so that at least have a starting point. I think you will still have to experience these things once, but you can be slightly better prepared to face them.",
        "speaker": "Viswanathan Anand",
        "start": 1833680,
        "end": 2002060,
    },
    {
        "text": "Yeah. This magazine story reminding you of, you know, in my own entrepreneurial journey, and that's a. Sometimes there's tendency to, you know, just go to the competitors, you know, whatever they are doing and obsess about what they are doing, why they are doing and so on. To the extent that you lose track of, you know, what you are trying to, what your game plan is at some point, actually 2011. Till I decide, I'll just not go to the competitor website, just I'm going to completely block it out of my mind. Only focus on if we have a game plan, we just execute see what happens. And I think that has created a lot of peace of mind for me. Otherwise it does, whether you say I'm not going to care, but it's still playing in your mind when you come back. That discussion I would in my team is very heavily colored by that. Why are they doing that? Why are we not doing this? Versus what do we truly believe in? Sting course. So I think that's basically what you feed your mind is very important. And I think all of us some control today with the mobile phones. If we don't pay attention, we are just consuming every possible variety of content and opinion continuously. I think people probably need to be very careful about what you expose yourself to and not to other things. Otherwise, you know, it will affect you how you think.",
        "speaker": "Mukesh Bansal",
        "start": 2002142,
        "end": 2065948,
    },
    {
        "text": "Yes. In fact, in terms of information, it's hard to see what is pure water and what is sewage. And in the modern media context, you have to assume that a good part of what you're reading is sewage, and some of it might actually be valuable, but unless you're very good at spotting, and invariably it's only people who are very, very highly specialized in that field who'll spot the good stuff. Otherwise, you just don't have the expertise to do it. And so you need a way of dealing with it. By the way, I can tell you with subsequent players, their reaction to this is not only to read what the other operators said, but to give it back as strongly, which is also a good strategy because you're fighting back. But the point is to be aware of it and do something that you have decided that you want to do, and then that's coherent as a strategy. What is not correct is saying, I don't care, but it's in your mind all the time. And mentally, you're answering the criticism. That's the worst place to be, and that's a mistake I made the first time, and I think I did better not replying in subsequent and looks like.",
        "speaker": "Viswanathan Anand",
        "start": 2066116,
        "end": 2133296,
    },
    {
        "text": "You know, I mean, speaking of, you know, knowing what is water and what's sewage, I think your book is, you know, absolute water. I think I have, I read it full four years ago and just kind of reread it, skim through this time. But I came across, you know, some stories and continue the same theme. You know, this, I think something similar happened to Karpov, also 98. I think you were seated next to him and he made some comment about, you know, wishy being a nice guy and so on, and that like rankled you at least talked about the story in your book.",
        "speaker": "Mukesh Bansal",
        "start": 2133320,
        "end": 2163120,
    },
    {
        "text": "Yes. So Karpov, it's a long story, but he managed to negotiate a deal with FIDE where I would have to compete six elimination rounds, where at any round, if I lost, then I was out of the competition, along with 128 other players. And then finally this player who won this, his first competition, then he would have to play against Karpov. Karpov's chest strength at that point didn't justify such a privilege. He was no longer the. He wouldn't even have been the strongest player in this knockout, but because of his status as a legend, they gave a tail. And the result was I had won this extremely strong knockout competition and I had a three day break before I could. I had to play Karpov, who had been resting in a beach resort for a while and raining and everything getting illegal. And this is the stuff that is simply unbelievable. With a straight face, Kapov spoke about how it had been hard for him because he had not been able to warm up. And on the contrary, I was very fresh from all this play. And he begged the obvious question, well, if you liked it so much, why you could have played with us? Why did you choose not to? But. And I sat there listening to this, almost as in disbelief. And the privileges he got did rankle. But then it's like someone who's obviously privileged, but contemptuous enough of that privilege to not even realize that he's been given a gift, someone who takes something unjustified for granted. But he understood the value of needling me and I didn't. And everything else is irrelevant, actually. It's a sport, it doesn't matter.",
        "speaker": "Viswanathan Anand",
        "start": 2163312,
        "end": 2279662,
    },
    {
        "text": "And finally you finally won in 2000. Was it against Karpov?",
        "speaker": "Mukesh Bansal",
        "start": 2279758,
        "end": 2283342,
    },
    {
        "text": "No, no. Karpov had long since, in fact, fide the vultures federation. After all the criticism, they removed his privilege the next time and said, well, you can play, but you'll have to start in the first round. And he was so upset, he sued them and didn't play after that. He never played after that because he had seen the writing on the wall. He was 49 at that time and he understood he's not going to be able to play against all these youngsters easily anymore. It was already very impressive. He had managed to go on that long. So as a chess playing legend, didn't change very much. But no, my subsequent rivals were all others. In fact, very quickly we moved to our generational conflict because Kramnik had beaten Kasparov in 2000, the same year I won the next knockout in Delhi and Tehran. And then the world took six years to reunify. I played a world championship in Mexico in 2007 where Kramnik had agreed to surrender his title in return for being guaranteed an entry into the match in 2008. And 2008 was when I became. I was undisputed champion in 2007, 2008, I became undisputed match champion.",
        "speaker": "Viswanathan Anand",
        "start": 2283518,
        "end": 2366648,
    },
    {
        "text": "Yeah, I remember in 2007 also, I think he was also not very gracious, I think, you know, like, I think he lost, but he said his temporary lent the title, something like that.",
        "speaker": "Mukesh Bansal",
        "start": 2366776,
        "end": 2376056,
    },
    {
        "text": "He loaned the title, he said, but by this time I was used to it. And also Kramnik is, I think, a genuinely nice person. I mean, he's someone I know very well. So even when he needled, we could both laugh about it. And so it stung less. And on top of that, I had started to take all these precautions, not reading websites and not reading chess magazines and all this thing. So by this point, I don't think it affected me anymore.",
        "speaker": "Viswanathan Anand",
        "start": 2376080,
        "end": 2407818,
    },
    {
        "text": "But throughout all this, you know, and I don't know whether it's part of, you know, maybe especially in Russia, maybe chess culture was slightly different. Maybe it was accepted part of the tournament tactics that different people will use. But you have cultivated a very professional, this genuinely nice person image. And I think people, a lot of people commend you, Sardar, for not any theatrics or anything, just 100% focus on the game. So somewhere this whole playbook of keeping to what you are there to do and also building this protection mechanism, maybe through some hard knocks along the way, has been a big part of how you've played the game.",
        "speaker": "Mukesh Bansal",
        "start": 2407866,
        "end": 2447664,
    },
    {
        "text": "At some point I realized the best thing is to be true to yourself, and for that, you must have an honest understanding of yourself. You can't pretend to be something you're not. Simply put, when Kapo would make these rubaks or Kasparov, I would often respond strongly afterwards, but it wasn't as effective. But I would respond afterwards in interviews and so on. And I sometimes used sharp language. Not, of course, I am too well brought up to get down into the battle, but, you know, I made it clear that I didn't think their points of view were valid and so on. And the worst thing was, after it finished, I went back home. I felt bad. I felt, did I not show respect to a great person? So then I realized, look, I'm not good at this. If I participate in this game, he's supposed to be feeling bad, not me. And so I think there's a famous joke of George W. Bush where he says, when you hunted, it's the animal that's supposed to suffer, not you. Okay, basically like that. I felt something like that. And so I decided, well, if I don't like it when I'm playing the game and I don't like it when they're playing the game, then I shouldn't play that game and I stopped doing it. There is some loss of ego where you agree to withdraw from a space, but the value in being not dissonant, there's no dissonance with yourself to being consistent and understanding yourself and being honest. And after that, you just feel, fine, this is who I am, and you have the confidence to make it a strategy. And then it's worked well for me, and I continue to be like that, and that's it.",
        "speaker": "Viswanathan Anand",
        "start": 2448044,
        "end": 2556824,
    },
    {
        "text": "Part of developing and growing is that developing this deeper relation of who you really are and coming to terms with it, then you are very much at peace and not really trying to do something that somebody else is doing, and because the, the fakeness of it will anyway come through. And you also feel, you know, a human do that very well. And as you said, you feel bad about, like, why am I even doing that? Right? I think I've seen multiple times, you know, again, in my own journey, at some point realizing this is who I am and just stop pretending to be anyone else. You know, the people who, like me care about me, they will accept me for who, you know, instead of me trying to fit in and do. And which is today, especially, again, youngsters feel so much pressure to fit in. This whole idea of FOMo, you know, now it has become a cultural status of its own, which is at some level can be very detrimental because taking you away from the inner journey and coming to terms with what do you really stand for?",
        "speaker": "Mukesh Bansal",
        "start": 2556944,
        "end": 2610256,
    },
    {
        "text": "Sure. And one fundamental truth, which I suspected all along, but became self evident, was it doesn't matter. Even if you don't match all the witty retorts and great commons and everything, at the end of the day, if you win, your opponent looks silly for having done it, and if you lose, he doesn't look silly for having been quiet. And if he did, if he played mental games, it doesn't matter. The only thing matters is the result. So then you think, well, let's focus on that and leave this stuff behind.",
        "speaker": "Viswanathan Anand",
        "start": 2610320,
        "end": 2644344,
    },
    {
        "text": "Absolutely. I think part of, you know, I mean, reading your book at this, you had this habit of going for the long walks. At some point you can say, I think you said you can walk across countries and continents and loss in thought. Is that part of your method to process your thoughts and let this thing play out in your head what roles these walks play in your journey to prepare and also put yourself in a certain mental state to be ready for these ultra competitive, high stakes games.",
        "speaker": "Mukesh Bansal",
        "start": 2644464,
        "end": 2677404,
    },
    {
        "text": "They're very important because the tension is building up constantly. Before, in the morning, before a game, you're thinking what are all the things that could happen? And you're panicking about all the areas. You feel under prepared and you're visualizing scenarios, but typically at the negative end of it, everything seems to go wrong in your head. So you're wound up. To be honest, I have often found arriving at the boat to be quite a relief, because finally you're dealing with reality. You're dealing with a physical opponent who's probably not going to do some crazy miracles. He's going to play a normal game of chess, he's pretty good, but it's going to be a normal game of chess. And all these scenarios melt away and then you get through the game, it's intense. Invariably you'll exchange mistakes, there'll be missed opportunities, and inside you're still fighting. So for a few hours afterwards there's an echo. You continue to the move that you missed bugs you. The mistake that you made, you know, your head is trying to come to terms with it. And I find these walks useful to settle down. Some of these men thoughts can have almost physical manifestations, like right before I play that movie, you squirm, but the game has long been over, but you feel it physically. And I found that these walks are a good way to, I don't think, dial back to zero, because at night I will still repeat the game a few times and so on. But it gives me a chance to say, to let go of some of that physical feeling and feel. And you feel this deep understanding. The only game that I can play now is tomorrow's game. And if I mess that up, I've only made it worse for myself. So let's, you know, it's part of the brain coming to terms with that, that your focus now has to be the next game. And this can go into the review ladder for much later, but that's where your focus has got to be. I also used to go to the gym after games and the idea was to exhaust myself so that at night, instead of replaying the game in my head, I would be too tired and actually go to sleep again. I say that good sleep is worth more than all the psychological training and all the other stuff. Not the chest training, but all the other stuff, because nothing like good sleep and good sleep has all these things built into it. If you sleep well, it means that psychologically you're in a good state, you're peaceful enough to your body to switch to something else. With sleep, it means you don't have worries about the next game. It means all those things that you've done things right, and it's almost a compressed form of doing the right thing. So that's the golden mean. And if you can feel in a good mood, generally cheerful, you have friends and family around who make you feel positive, and you do the things that you associate with prior positive experiences, and you don't do the things that went wrong in the past. Even if there's no rational connection, you try to accentuate the positive because invariably these things accumulate. And during the game, at some point it could make a difference.",
        "speaker": "Viswanathan Anand",
        "start": 2679064,
        "end": 2880526,
    },
    {
        "text": "Yeah, both of these are, you know, walking asleep. I think they're probably underrated, were extremely powerful tools, I think, for walking. I remember probably going to butcher the court, but a very famous philosopher said the leisurely walks are the most powerful way of producing very high quality thought and I think also can calm you down, you can process things and so on and sleep again. In my second book, Hacking Health, I think sleep is something I stress the most. If people can do only one thing for their health, just sleep for seven, 8 hours and it automatically cuts down, you know, just makes rest of day so much easier. So Anand, speaking of walking, I think I remember reading another story where I think this was, I forget who the opponent was, but you were pretty upset, something about a Berlin move, and you were having this walk where you were quite annoyed. I think you walk with your wife and you had a very interesting exchange, which I think doused the situation very quickly.",
        "speaker": "Mukesh Bansal",
        "start": 2880670,
        "end": 2941674,
    },
    {
        "text": "Yes. So I was very wound up and because I lost that game and had a very bad start in the tournament as well, to make it even worse, two years ago I played in this tournament and I had the worst result of my life. So if you feel this bad, start with that. It looks even worse. So I went for a walk with my wife, and my wife normally tries to cheer me up, saying something like, you know, don't worry about it, it'll get better, you know, it's gone better in the past. Something she'll try to say something we both know you can't, you know, take it to the bank, but, you know, you feel a bit better this time. I think she just given up because it was then she herself was being a bit quiet. But I'm sitting there waiting for her to say something, you know, almost as get it over with, you know, you're used to it. So I said, what, are you not going to say anything? She said, if you want it. So she said, well, it'll, you know, hang in there, forget about it, and play well. And I told her, yeah, that's all very well, I know that, but it's not. It doesn't seem to be doing me any good. If, you know, the refutation of the Berlin defense, you know, that might be more helpful. And she was quite annoyed because she said I was being silent because I thought this advice is redundant. And then she asked me for it. I tell it to you and then you snap at me. So she came up with this thing. She said, if I knew the reputation of the Berlin defense, why the hell am I married to you? So. And then a bit later, we both smiled and we understood that I'm warned up. She's warmed up. It wasn't really happening, but it somehow seemed very funny. And then we went back and funnily enough, it was very helpful because I then decided to start that tournament as if it was starting in the fourth round. So the first three rounds had been a disaster. But what I had understood is I've got to play the next seven rounds whether I like it or not. So you might as well do the best job you can and then go home afterwards and kick yourself in peace. So the idea was, let's pretend that the game starts in the fourth round. In fact, in the fourth round, I made a pretty bland draw against Kramnik just to stop losing. And then I won three games in a row because I started thinking of it as a new tournament and you wipe the slate clean and something like that. I was doing some experience, so it was. It also led to positive things.",
        "speaker": "Viswanathan Anand",
        "start": 2942054,
        "end": 3107034,
    },
    {
        "text": "But anyway, so after, you know, tough loss or a difficult situation, when you are brooding about situation, I think both being able to have a, in some ways, just conversation, talk to someone who is empathetic, you know, just talk it out is probably helpful. And also maybe see the, you know, levity in the situation. And sometimes just a little laugh off is also help you versus, you know, we can stay wound up for a very long period of time and keep, you know, replaying what happened or what might have been and so on, where some of these things can help you just snap out of it and in a different frame of mind.",
        "speaker": "Mukesh Bansal",
        "start": 3107074,
        "end": 3135580,
    },
    {
        "text": "Yes. Some of my best trainers have this skill that when you're in that situation, they'll crack a joke about something which is just very funny. This is often a good time to see your old schoolmates, because then the conversation goes into another timeframe. It's unsaid and unspoken that nobody has an answer to your predicament. But what you are conveying is, well, let's laugh a little bit, because we can't change where you are. So you come to terms somehow. And it does help. Again, the technical recovery will follow very fast after the emotional recovery. But the emotional recovery holds back any chess execution that I can do. So being able to come to terms, you know, the stages of grief. Acceptance is the most important. That's the one where you haven't solved anything, but you accept exactly what it is.",
        "speaker": "Viswanathan Anand",
        "start": 3135732,
        "end": 3196316,
    },
    {
        "text": "Yeah, see, chess is a game which also requires, you know, this intense period of preparation. I think, I don't know, maybe things are speeding up now. But if I recall correctly, in the past, some of your world championship games might prepare up to a year or six months to one year period. That's very uncommon. Most things in life are not that you have something which coming up, which is very high stakes situation, and then you are just heads down, preparing, preparing. And the two parts maybe so one is that what was your approach to those preparation period in terms of focusing on that, staying in the moment, knowing fully well you are going to be on the world stage. And also with that preparation, how much the balance between going with a very clear plan of what you will do, but thinking on the spot also as the game evolves after or doesn't moves. I guess it's a wide open problem how much you're still going back to preparation versus being in the moment and just playing with intuition.",
        "speaker": "Mukesh Bansal",
        "start": 3196340,
        "end": 3257924,
    },
    {
        "text": "So that's a very nice way of putting it. The dream, of course, is to be well prepared, to know exactly what you're supposed to do. But another way of putting this is that being well prepared is simply an attempt to avoid the worst scenarios. You avoid the worst scenarios by being well prepared. So that then if when you dropped, inevitably, as you will be dropped in an unfamiliar situation, you're able to deal with it confidently. So I'll use language as an analogy. Every chess player plays a part of the game and has expertise in certain parts of the game, like a mother tongue. But then we are constantly trying to add other skills, other parts of the game. And those invariably feel like a second language and a third language where you can learn something, but the application is not that fast. The first line, the mother tongue always feels more fluent. The newer languages, there's always a lag. You'll make mistakes. And even the ability to attempt conversation while not being conscious of your mistakes is a skill. Okay, so. But the dream is to get more and more intuitive, as intuitive as your mother tongue is. In fact, when you speak your mother tongue, you're not thinking of grammatical rules. You just know the next word pops into your head. That's what you're looking for. That's why we train for a year, because we will have a game plan and the technical work will be done fairly fast on paper. But then my thing is to go over that material over and over again. In the context of a game where I don't get any external assistance, I have to figure everything out my own. And only then you understand which are the questions that are blocking you and which are the ones you're able to answer. And then you go with the material once. Okay, now I got it. And then you try again. And then you're going back and forth, back and forth, trying to convert this knowledge into some intuitive understanding, because you cannot. You may control the first 20 moves, even the 23rd move, but sooner or later you'll have to play ten or twelve moves on your own. But those moves are related to the moves that have come before, so they fall into a certain pattern, and you need to familiarize yourself, look at the position over and over again, play many games, and you get that intuitive feeling. And so that's what. But all chess growth is like that for a match. You just do a lot of it because the stakes are very high. But it's the same process everywhere. And you're always trying to convert everything into intuitive understanding, because that's the only real value you have. What can you say when you're not prepared at all? That's the golden.",
        "speaker": "Viswanathan Anand",
        "start": 3259064,
        "end": 3427032,
    },
    {
        "text": "Yeah. Can you give a peek into, maybe look back into time where maybe your most intense training period ever? And what did your day to day look like? The intensity and the method of preparation. If you just visualize a typical day.",
        "speaker": "Mukesh Bansal",
        "start": 3427208,
        "end": 3444536,
    },
    {
        "text": "In my first serious training was with a player called Mikhail Gorevich, who had been a second of Kasparov in his matches. And he was multiple times soviet champion. Just after the fall of the Soviet Union, he had emigrated and he was living in Belgium, so I went to have a training camp with him. This is pre computer era. So then we first decided that my main opening, at that point, I should stop playing it. I had come to this conclusion myself, because what I understood was in the opening, that I was most fluent at Kapo was even more fluent, and he was going to be more permanent. So we decided, well, this one is too easy for him, and if it's easy for him, it will turn out to be more easy for him as it goes along. So let's move away and find something where the problems posed are more complex and unfamiliar to him, even at some risk to yourself. So, fairly straightforward strategy. We then made a list of all the positions we would need to study. Very, very small amount of work compared to modern material. Because of the computer, you can generate a lot of stuff. But anyway, we did this work, looked at some systems. I remember I used to have the habit of training until then, but with doing some other things on the side, what we call multitasking. So at some point I asked, I told Misha, there's an episode of Star Trek, so can I leave it on and we'll work? He looked a bit surprised, and I think the sternest voice so far. He told me, if I can leave and come back when the Star Trek is over, but we cannot do two things at palace. So then you see, you know, and I mean, I understood his point, and I thought, it's a pity I'm missing this episode, because not in the days where you can simply replay them anywhere, right? So I kind of understood his point, and I got back to work. And by the way, it's not even, I think, with experience, I would say that my math approach is not totally wrong. Nobody can work 6 hours in a row, so you might want to schedule that break once in a while. That's fair enough, but you could see that that was a big difference. In 2008, we did some of our best work, and I think it's still the best match I played and prepared for very similar situation. I was playing Kramnik this time, and I understood that my main opening is very badly suited to playing against him. The stats were something like, I had beaten him seven times, he had beaten me nine times, but I had beaten him three times with the white pieces and four times with the black pieces. He had beaten me nine times with the white pieces, so he had never beaten me in black, but with white, I was not making any headway. He's a three to one ratio in terms of wins. With black, I was punching a gun. So this suggested an obvious strategy, which is with black, to be aggressive. That was fine. That was always my strategy against him. I just had to build on it. But with White, I understood that my main opening doesn't work against him. He's very good at neutralizing it. Clearly, I feel uncomfortable, very unlike the situation. Kapu would have faced. So, in effect, the suggestion was, well, why don't you switch to a second language? Switch to something you don't play often, where it's not that intuitive. You will be often in unfamiliar situations, but it's harder for him. So once we took this decision, we decided it's not the sort of thing you can spend one month on and then review work. It's a commitment you'd make. Now you decide right away, are you going to go all in or not? So the idea was we would switch and not revisit this decision, no matter how bad it got. So in, we spent some months working on the second opening and played it against Kramnick. And just like a second language, it was often unfamiliar. I would have to think, what would I do now? As you think, what's the next word? How do I construct that sentence? And so on. It's a bit harder for you, but at the same time, you're not on autopilot and you don't tend to do lazy moves, and that also has a positive effect on your chest, and it's more creative because you're thinking all the time and so on. Your sense of danger is heightened. It remains the best match I've played. And we also had one little advantage the previous year. In 2007, when I was playing the world championship. These people decided to have the world computer championship at the same time, two floors below us. So one day after I finished my game, we decided to go for a walk and we went down a couple of floors to see how the computers were playing.",
        "speaker": "Viswanathan Anand",
        "start": 3444720,
        "end": 3742864,
    },
    {
        "text": "Is it computer against computer?",
        "speaker": "Mukesh Bansal",
        "start": 3743644,
        "end": 3745116,
    },
    {
        "text": "Computer against computer? This is the world computer championship. And we realized a lot of them are working on laptops, not very. We expected to see a lot of high end hardware, so we asked them, how do we do it? They said, no, I've got the high end hardware at home and we have DC IP protocols that we are running it there, but playing the moves here. And we were amazed because we had never heard of this and it was still not common. Within a year, because of what I did in the match, everyone started doing it. But in a sense, by this chance encounter, we found out about this thing. And so later, when I was preparing for Kramnik, we inquired, can I have access to some very powerful hardware running somewhere else? And some trial and error? But we figured out how to use it. And so we were using this excellent hardware to game all the most risky approaches. I could try and do that match. I'll tell you my routine. There was a flight of stairs 153 steps up over three streets. So my thing was to go to the bottom straight, run up incredibly fast, all 153 steps to exhaustion, then slowly walk down, then again run 153. I was doing this and also sometimes running in the park every morning like a 1 hour thing. We will start at eleven. First eleven till 1230. 1245 was kind of sluggish work. But we are also brainstorming. Can work on this today, that today, whatever. Then lunch break which everyone was looking forward to. We'd go have lunch, but lunch again pleasant. We're all dining, I mean having, ordering together, chatting and then we come back. Then a serious session, three to maybe seven or something like that. That's a big stretch, 4 hours then very important to take a nice walk. By now it's cooled off. So a nice walk then dinner or in the reverse order and come back at nine or 930 and then do one more session till midnight. This we repeated six days a week. 7th day nobody. Everyone slept late, did nothing. One day even, no exercise, just recovery. We did this routine for, I think it was July, August. Then there was a break in September. In October I had a brief review session and then we went off to play the match. So six to eight weeks was the training I used to do. Nowadays the fashion is to do two weeks stop. Then a couple of weeks later you do another two weeks stop. Because the nature of work has changed and this is what people prefer, but you know, that's what.",
        "speaker": "Viswanathan Anand",
        "start": 3745180,
        "end": 3925360,
    },
    {
        "text": "But thanks for sharing. See, I'm always amazed Anand that in the, you know, in the professional sports the emphasis on training is so important. Well, in real life, most of our work, we just show up and somehow expect to perform and get better. So I think this recognizing it doesn't matter if I want to perform at a better level than today, then I have to put in conscious effort to train also may not be able to train like a world class sports person, but can still train whether it's 1 hour a day or few hours on the weekend or something. But without that, you know, just without training, you know, you're just not going to get better. Whatever you're trying to do.",
        "speaker": "Mukesh Bansal",
        "start": 3925392,
        "end": 3963560,
    },
    {
        "text": "Yes, very much. I think even for smaller goals, setting aside a day or two where you try to significantly improve your performance is nice because then that improvement becomes a new kind of baseline to which we can't do it all the time. But every once in a while it's good to push yourself like that, right?",
        "speaker": "Viswanathan Anand",
        "start": 3963712,
        "end": 3984792,
    },
    {
        "text": "I was, you know, in this preparation for this episode, I was talking to a friend of mine, he's a VC, but also huge chess enthusiast. Asked him, what is something interesting I can ask? So he told me something I was not familiar with this thing called Zook Zwang.",
        "speaker": "Mukesh Bansal",
        "start": 3984968,
        "end": 3998240,
    },
    {
        "text": "Zook Zwang, yeah.",
        "speaker": "Viswanathan Anand",
        "start": 3998392,
        "end": 3999416,
    },
    {
        "text": "So he was, you know, ask him about that, because sometimes it feels like, you know, you run into those situations in real life as well. So first of all, can you explain what that is? And do actual players run into those situations?",
        "speaker": "Mukesh Bansal",
        "start": 3999480,
        "end": 4010292,
    },
    {
        "text": "So Zug is a move, and Swang is essentially being in a situation where you're forced to do something. This is also the root of the word svangar, which is pregnancy. Anyway, I think the word is what? Earthswingen. But to be obliged to. So Zugzwang is the most tragic situation. You're absolutely fine. Your pieces are in the best squares, but it's your move, which means you have to worsen your position. And it turns out there are positions where you can shift, you can make a move, and it doesn't worsen your position because there are two or three states, but there are positions where everything is perfect. And if it's your opponent move, you're doing great, but it's your move. So you have to just kill yourself, essentially, you have to stab yourself. And so Zugzwang is a very painful situation to be in, but it's also a very natural part of the game of chess. A lot of endgame build on Zugzwang, where basically you end up in the position, then you make the move and your opponent's move is going to destroy his position. That's a very normal thing.",
        "speaker": "Viswanathan Anand",
        "start": 4010448,
        "end": 4078358,
    },
    {
        "text": "That's a good parallel for real life. We have the advantage of sometimes not doing anything. If in the situation, sometimes we feel like the only way out of a situation is to do something. But maybe sometime recognizing not doing anything, just waiting it for a week or a month, maybe a better move, which you can't do. You have to play in what's in your.",
        "speaker": "Mukesh Bansal",
        "start": 4078406,
        "end": 4095366,
    },
    {
        "text": "That's right. It's a good point because it's also a very nice concept, action bias. You feel you have to do something, but sometimes doing nothing itself can be a good move.",
        "speaker": "Viswanathan Anand",
        "start": 4095430,
        "end": 4109766,
    },
    {"text": "Right?", "speaker": "Mukesh Bansal", "start": 4109830, "end": 4110078},
    {
        "text": "Right. It's an art.",
        "speaker": "Viswanathan Anand",
        "start": 4110126,
        "end": 4111838,
    },
    {
        "text": "Right. So Anand, if you zoom out and you look back on your career as a professional chess player and having accomplished everything you have done, and also now helping move the game of chess forward by working with the younger generation for you, what are some of the two or three learnings? Or how is the game of chess shaped you, who you are?",
        "speaker": "Mukesh Bansal",
        "start": 4112006,
        "end": 4134323,
    },
    {
        "text": "Chess has clearly been the dominant way that I have faced the world, and therefore also every little trick I've learned to deal with any situation in life, I feel has its origin in some chess game and some lesson from that. Again, that's a very natural statement to make, because the way I deal with things in chess is based on the way I deal with everything. It's who I am. One thing I realize is that because of my training in chess and because I am very good at chess.",
        "speaker": "Viswanathan Anand",
        "start": 4136663,
        "end": 4178434,
    },
    {"text": "I.", "speaker": "Mukesh Bansal", "start": 4182694, "end": 4183006},
    {
        "text": "Get away with a lot. And in the rest of in other areas, I don't get away with a lot. So in everyday interactions, I often tell myself I can't be impulsive thing because in chess, my worst move is still not a very bad one. But so you have to keep that balance. What else? Obviously, these days I experience a lot of nostalgia. I often think things were wonderful 30 years ago, probably not so, but you remember all those things, but you can draw a very straight line and the feedback is constant. You'll face a problem in life, and your emotional response is exactly the same when you face that same problem in chess. But the training there helps me cope much better. And if you can train these kinds of things in everyday situations, you will get better at that as well. And I make mental notes all the time. If I have an unpleasant encounter with someone, I try to think, is there something I could have done, or is there something they could do, or should I just avoid this meeting in future and the next time I'll do that? It's a bit pavlovian because you'll often transmit it, but I think it's worth examining at least.",
        "speaker": "Viswanathan Anand",
        "start": 4183030,
        "end": 4260560,
    },
    {
        "text": "Amazing, and thanks for taking the time for talking to us. I think yours is an incredibly inspiring story. I think you've stayed relevant to the game for many decades. I think you still have a lot more to give to the game, both as a player. I'll highly recommend your book. I think there's so many interesting life lessons while you have chess stories. I think most of the lessons are quite relevant to everyday life, so I'll recommend that. And you are always very humble, down to earth. You are very open to share your experience of learning with the people, and it's just an honor to be able to talk to you. Anand, thank you so much.",
        "speaker": "Mukesh Bansal",
        "start": 4260712,
        "end": 4296388,
    },
    {
        "text": "Thank you so much. It was very pleasant.",
        "speaker": "Viswanathan Anand",
        "start": 4296476,
        "end": 4298104,
    },
    {
        "text": "At Sparks, we aim to bring to you stories of exponential impact. We share in depth analysis of what goes behind success stories. If you find our conversations interesting, you can join us by subscribing to our YouTube channel. You can also listen to Sparks on Spotify, Apple Podcast or any other audio platform of your choice. If you have any suggestions on who we should invite or what topics we need to cover, just let us know in the comments. We are always listening, looking for ways to improve and keep getting better as we go along.",
        "speaker": "Mukesh Bansal",
        "start": 4304694,
        "end": 4333694,
    },
]
